# Generated by Django 3.2.2 on 2023-08-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cantidad', models.CharField(default='deseados', max_length=120, verbose_name='cantidad')),
                ('title', models.CharField(default='', max_length=120, verbose_name='title')),
            ],
            options={
                'verbose_name': 'WishList',
                'verbose_name_plural': 'WishLists',
                'db_table': 'wish_list',
            },
        ),
    ]
