# Generated by Django 3.2.2 on 2023-08-08 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e_commerce', '0002_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='title',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='comic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='e_commerce.comic'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
