# Generated by Django 3.2.2 on 2023-08-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_auto_20230808_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='bought_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='bought qty'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='cart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wished_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='wished qty'),
        ),
    ]
