# Generated by Django 3.2.2 on 2023-08-08 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0004_auto_20230808_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='comic',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='e_commerce.comic', verbose_name='Comic'),
        ),
    ]
